import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ka-Ching!</h1>

        <p className={styles.description}>The Solana on-chain PoS</p>

        <div className={styles.grid}>
          <Link href="/admin" className={styles.card}>
            <h2>Admin &rarr;</h2>
            <p>Connect your wallet and start managing your PoS</p>
          </Link>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>End-to-End Demo &rarr;</h2>
            <p>See how it all works for your end users</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
