[features]
seeds = false
skip-lint = false
[programs.localnet]
kaching_cash_register = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/tompere/.config/solana/id.json"

[scripts]
test = "yarn jest --testTimeout=120000"
